name: Build
run-name: Build
permissions: read-all
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run tests
        run: go test -count=1 -race ./... -coverprofile ./coverage.txt
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: energimind/powermesh-core
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Run markdownlint
        uses: avto-dev/markdown-lint@v1
        with:
          args: "README.md"
